version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
      tags: 
        - mariadb:v1
    image: mariadb:v1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=123456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
      tags: 
        - wordpress:v1
    image: wordpress:v1
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_URL=jiyunpar.42.fr
      - WORDPRESS_ADMIN_USER=jiyunpar
      - WORDPRESS_ADMIN_PASSWORD=1234
      - WORDPRESS_ADMIN_EMAIL=gyp2795@gmail.com
      - WORDPRESS_USER=jiyun
      - WORDPRESS_USER_PASSWORD=1234
      - WORDPRESS_USER_EMAIL=gyp93@naver.com
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app_network

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
      tags:
        - nginx:v1
    image: nginx:v1
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - app_network

volumes:
  wordpress_data:
  db_data:

networks:
  app_network:
