version: "3.9"

services:
  mariadb:
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    restart: always
    volume:
      - DB:/var/lib/mysql
    networks:
      - wordpress_mariadb

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    restart: always
    volume:
      - WordPress:/var/www/wordpress
    networks:
      - wordpress_mariadb
      - nginx_wordpress

  nginx:
    depends_on:
      - mariadb
      - wordpress
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - nginx_wordpress

volumes:
  DB:
  WordPress:

networks:
  nginx_wordpress:
  wordpress_mariadb:

# secrets:


# configs:
